# Làm việc với mảng ngẫu nhiên
- Mảng ngẫu nhiên các số tuân theo phân bố đều
- numpy.random.rand: là một mảng ngẫu nhiên mà mỗi phần tử là một số ngẫu nhiên có phân bố đều

# Numpy
1.1) Khai báo vector được hiểu như mảng 1 chiều
1.7) Norm 1: được định nghĩa bới giá trị tuyệt đối của tổng tất cả các phần tử trong vector
1.8) Hàm softmax trong mảng 1 chiều: là một trong những thuật toán được sử dụng nhiều nhất trong các bài toán classification: a[i] = e^(z[i])/ Sum(Z[i]): các phần tử của hàm softmax đều nằm trong khoảng (0, 1) và có tổng = 1, vì vậy a còn được gọi là vector xác suất.
1.9) Norm 2: tích vô hướng của hai vectors, (căn của tổng bình phương tất cả các phần tử)



In [52]:
import numpy as np
x = np.array([1, 2, 3])
x

# TODO
x= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x
# -- end TODO --
a = np.array([1.0, 2.0])
a
type(a[0])

# Khởi tạo mảng 1 chiều đặc biệt
# Mảng chỉ gồm giá trị 0
zeros = np.zeros(5)
zeros

# Mảng chỉ gồm giá trị 1
ones = np.ones(6)
ones

# Tạo mảng 0, 1 có cùng chiều dài (zeros_like, ones_like)
zeros_like = np.zeros_like(ones)
zeros_like

# Cấp số cộng
a = np.arange(3, 6, 0.1)
a

# Xây dựng 1 mảng lũy thừa của 2 nhỏ hơn 1025 bao gồm 1 = 2**0
n = 0
while (2**n <1025):
    n += 1
2**np.arange(0, n, 1)

# Xây dựng mảng 10 phần tử, trong đó 9 phần tử đầu = 3 phần tử cuối = 1.5
n = 10
a = 3 + np.zeros(n)
a[n-1] = 1.5
mean = np.mean(a)
for i in range(a.shape[0]):
    a[i] = mean
a


array([2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85])

In [53]:
# Truy vấn mảng 1 chiều
import numpy as np
x = np.array([3, 4, 5])
x[-1]

5

In [80]:
# Truy cập nhiều phần tử trong mảng 1 chiều
a = 0.5*np.arange(10)
ids = [1, 3, 6]
a[ids]

n = 4
a = np.zeros(n) -1
b = np.arange(2, 2-0.5*a[::2].shape[0], -0.5)
a[::2] = b
a

array([ 2. , -1. ,  1.5, -1. ])

In [90]:
import math
# Tính toán giữa mảng 1 chiều và một số vô hướng
x = np.array([1, 2, 3])
y = math.pi/2 - x
z = np.sum(np.cos(x) - np.sin(x))
z

-2.757725446972893

In [98]:
a = 0.5*np.arange(10)
a[::2] = a[::2] * -1
np.sum(np.abs(a))

22.5

In [102]:
a = 0.5*np.arange(10)
b = np.exp(a)/ np.sum(np.exp(a))

1.0

In [109]:
# Tìm giá trị max, min, argmax, argmin
a = np.arange(10)
a

a[-1] = -2
np.min(a)
np.max(a)

# Tìm chỉ số mà mảng 1 chiều đạt giá trị nhỏ nhất, lớn nhất
np.argmin(a)
np.argmax(a)

8

# == #
- Mutable: Có thể thay đổi
- Immutable: Không thể thay đổi

# Làm việc với ma trận


In [110]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
# Ma trận đơn vị và ma trận đường chéo
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
# Ma trận đường chéo
np.diag([1, 3, 4])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [116]:
# Tạo ma trận với đường chéo phụ
n = 10

np.diag(np.arange(n), k=-1)

# Truy cập vào từng phần tử của ma trận trong mảng 2 chiều

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0]])

In [121]:
A = np.array([[1, 2], [3, 4]])
def myfunc(b):
    return np.sum(b[:2,:])

myfunc(A)

10